# Site settings
title: Doga Gursoy
email: dgursoy@aps.anl.gov
github_username: dgursoy

description: > # this means to ignore newlines until "baseurl:"
  Assistant Computational Scientist<br>
  Advanced Photon Source<br>
  Argonne National Laboratory<br>
  9600 South Cass Avenue<br>
  Lemont IL 60439

# the base hostname & protocol for your site
url: "http://dgursoy.github.io" 

# the subpath of your site, e.g. /blog
baseurl: "" 

# Build settings
markdown: kramdown
